let fps1: [
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications/Calendar.app",
        size: "256.5mb",
        tester: "Perter",
        priority: "L4",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications/Chrome.app",
        size: "496.7mb",
        tester: "Chloe",
        priority: "L4",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications/Webstorm.app",
        size: "128.6mb",
        tester: "Adrian",
        priority: "L4",
    },
    {
        type: "folder",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications/Webs",
        size: "",
        tester: "",
        priority: "",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications/Webs/web_infors.json",
        size: "92.2kb",
        tester: "Carl",
        priority: "L3",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications/Webs/Shareco/s1.txt",
        size: "5.4kb",
        tester: "Charissa",
        priority: "L4",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications/Webs/Shareco/s2.txt",
        size: "7.3kb",
        tester: "Dexter",
        priority: "L4",
    },
    {
        type: "folder",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications/Webs/Guess",
        size: "",
        tester: "",
        priority: "",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications/Webs/Guess/s3.txt",
        size: "21.6kb",
        tester: "Ashley",
        priority: "L4",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications/Webs/Guess/s4.txt",
        size: "82.7kb",
        tester: "Dwight",
        priority: "L4",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/Regulator.ini",
        size: "2.5kb",
        tester: "Laura",
        priority: "L5",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications/Systems/Regulator/vers/settings-v01.st",
        size: "56.2kb",
        tester: "Mavis",
        priority: "L5",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications/Systems/Regulator/vers/settings-v02.st",
        size: "87.2kb",
        tester: "Geraint",
        priority: "L5",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications/Systems/Regulator/vers/settings-v03.st",
        size: "224.2kb",
        tester: "Penelope",
        priority: "L5",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications/Systems/Regulator/vers/settings-v04.st",
        size: "72.7kb",
        tester: "Heman",
        priority: "L5",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications/Systems/Regulator/vers/settings-v05.st",
        size: "91.2kb",
        tester: "Tessa",
        priority: "L5",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device01.iso",
        size: "1.2gb",
        tester: "Una",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device02.iso",
        size: "1.3gb",
        tester: "Jasper",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device03.iso",
        size: "1.1gb",
        tester: "Violet",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device04.iso",
        size: "1.7gb",
        tester: "Perter",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device05.iso",
        size: "2.0gb",
        tester: "Winifred",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device06.iso",
        size: "1.7gb",
        tester: "Lance",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device07.iso",
        size: "2.1gb",
        tester: "Marvin",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device08.iso",
        size: "1.5gb",
        tester: "Nat",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device09.iso",
        size: "1.8gb",
        tester: "Nahum",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device10.iso",
        size: "1.6gb",
        tester: "Nicholas",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device11.iso",
        size: "1.2gb",
        tester: "Ralph",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device12.iso",
        size: "2.2gb",
        tester: "Rudolph",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device13.iso",
        size: "1.9gb",
        tester: "Rory",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device14.iso",
        size: "1.2gb",
        tester: "Jacqueline",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device15.iso",
        size: "1.7gb",
        tester: "Kathy",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device16.iso",
        size: "1.1gb",
        tester: "Melinda",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device17.iso",
        size: "1.9gb",
        tester: "Sharon",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device18.iso",
        size: "1.2gb",
        tester: "Philippa",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device19.iso",
        size: "1.5gb",
        tester: "Thelma",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Applications//Systems/device20.iso",
        size: "1.4gb",
        tester: "Stewart",
        priority: "L2",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Documents/design-simple/src/index.txt",
        size: "6.7kb",
        tester: "Steve",
        priority: "L1",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Documents/design-simple/src/bootstrap.txt",
        size: "251.7kb",
        tester: "Theobald",
        priority: "L1",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Documents/design-material/src/btn.txt",
        size: "241.2b",
        tester: "Padraic",
        priority: "L1",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Documents/design-material/src/card.txt",
        size: "4.7kb",
        tester: "Napoleon",
        priority: "L1",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Documents/design-material/src/window.txt",
        size: "7.2kb",
        tester: "Lionel",
        priority: "L1",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Downloads/October.pdf",
        size: "16.9kb",
        tester: "Olive",
        priority: "L1",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Downloads/November.pdf",
        size: "94.5kb",
        tester: "Molly",
        priority: "L1",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Downloads/Tutorial.html",
        size: "22.7kb",
        tester: "Melanie",
        priority: "L1",
    },
    {
        type: "folder",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Uploads",
        size: "",
        tester: "",
        priority: "",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Videos/Tutorials/Basic layouts.mp4",
        size: "862.7mb",
        tester: "Lindsay",
        priority: "L3",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Videos/Tutorials/Advanced techniques.mp4",
        size: "626.5mb",
        tester: "Jarvis",
        priority: "L3",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Videos/Tutorials/All about app.mp4",
        size: "796.2mb",
        tester: "Gaston",
        priority: "L3",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Videos/Intro.mov",
        size: "852.8mb",
        tester: "Dermot",
        priority: "L3",
    },
    {
        type: "file",
        path: "/aaa/bbb/ccc/ddd/eee/fff/ggg/hhh/iii/jjj/Videos/Conference introduction.avi",
        size: "676.7mb",
        tester: "Hector",
        priority: "L3",
    }
]
